spring.application.name=LearningSpringBoot
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/aangupta/Downloads/SpringBoot/ModuleCodes/LearningSpringBoot/db
spring.datasource.username=aangupta
spring.datasource.password=MrSandy@123
spring.jpa.hibernate.ddl-auto=update
